// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMo6SOkAQzUM-maEDbfMh_nRLHw09CJPU',
    appId: '1:460316917916:web:41a7dca902146d5a0f6d59',
    messagingSenderId: '460316917916',
    projectId: 'homeops-agent-8a1e9',
    authDomain: 'homeops-agent-8a1e9.firebaseapp.com',
    storageBucket: 'homeops-agent-8a1e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMdJ9rTAgWDoMv0FzZxweq-1bYdcSzwxs',
    appId: '1:460316917916:android:b0cb58e9be09fd710f6d59',
    messagingSenderId: '460316917916',
    projectId: 'homeops-agent-8a1e9',
    storageBucket: 'homeops-agent-8a1e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVGZv52YP-ByEUHuJpAgvbkLq698XBzsk',
    appId: '1:460316917916:ios:f727e1f5107d2eb10f6d59',
    messagingSenderId: '460316917916',
    projectId: 'homeops-agent-8a1e9',
    storageBucket: 'homeops-agent-8a1e9.firebasestorage.app',
    iosBundleId: 'com.example.homeOpsAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVGZv52YP-ByEUHuJpAgvbkLq698XBzsk',
    appId: '1:460316917916:ios:f727e1f5107d2eb10f6d59',
    messagingSenderId: '460316917916',
    projectId: 'homeops-agent-8a1e9',
    storageBucket: 'homeops-agent-8a1e9.firebasestorage.app',
    iosBundleId: 'com.example.homeOpsAgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMo6SOkAQzUM-maEDbfMh_nRLHw09CJPU',
    appId: '1:460316917916:web:9d09ab13015306180f6d59',
    messagingSenderId: '460316917916',
    projectId: 'homeops-agent-8a1e9',
    authDomain: 'homeops-agent-8a1e9.firebaseapp.com',
    storageBucket: 'homeops-agent-8a1e9.firebasestorage.app',
  );

}